### ISSUE TITLE
Missing paths in presets

### ISSUE THREAD

**Issue by taupo19** [nerk987/txa_ant#8]
In Blender 2.92 it reports 'missing paths' in the presets

**Comment by nerk987** [comment]
It's working for me in Windows, versions 2.92 and 2.93.

Would you mind being more specific? 
  - operating system
  - scripts path set in preferences?
  - Which presets? The main noise presets or the erosion presets?

Wherever the addon is installed, are the folders there for presets, mainpresets and materials?

**Comment by taupo19** [comment]
Thank you for replying - here's some more details
OS = Windows 10
Path = C:\Users\taupo\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\txa_ant
The presets that are reporting missing are the Main Presets - the various landscape forms.
The folders in the above location are:
![image](https://user-images.githubusercontent.com/50077276/119888052-e0e04000-bf6f-11eb-940d-833ed2c1581d.png)
Not sure if the above pasted image will work??

Hope this helps. I also have the ANT landscape addon but have disabled it in preferences - maybe a conflict?

**Comment by gaetgu** [comment]
I am having the same issue.

**Comment by nerk987** [comment]
I've been looking at this problem. It's a bit tricky. Blender's preset system is not that well documented. The A.N.T. addon is installed with blender and the presets are in a different location to the addon, so I had to change how this worked.

I think the issue is probably a missing directory. There needs to be a 'presets' directory in ...Blender\2.92\scripts as well as the "addons" directory. @taupo19 (and @gaetgu ), could you please confirm that the 'presets' directory is not there?

If the 'presets' directory is not there, please use the txa_ant addon to create a landscape. Then from the "TXA Landscape" panel on the right hand side, expand the "Eroder Params" panel. The "presets" directory should then be created automatically (to allow the "Erosion Presets" to work). The main presets should work the next time a txa_ant landscape is created.

If you could please confirm this fixes the issue, I'll make a revision that creates the presets directory as soon as the landscape is created.

**Comment by taupo19** [comment]
Thanks for the suggestion  - I did what you suggested and everything seems
fine now. I am able to generate a variety of landscapes in both versions.

Thank you for the support,

Andy

**Comment by nerk987** [comment]
Thanks for testing @taupo19. I've added version 2.91.1 to create the presets directory before the main presets panel comes up. It's only applicable when using the addon for the first time.
