### ISSUE TITLE
Traceback (most recent call last)

### ISSUE THREAD

**Issue by problems-2** [nerk987/txa_ant#9]
When ever I install the addon it gives me the error how do i fix this?

**Comment by PetrKnedlik** [comment]
Having the same issue

**Comment by nerk987** [comment]
Sorry, but that gives me absolutely nothing to go on. The words "Traceback (most recent call last)" appear with every type of error message.  From the window menu, go to 'Toggle System Console' and copy the whole error message. There will be several lines of text at least.
It would also be useful to know whether you are using Windows, Linux or Mac, the version of Blender and the version of the TXA_Ant addon that you're trying to install.

**Comment by PetrKnedlik** [comment]
Thank you for replying so fast! :)
Sorry, you are right. I thought that since it's already existing issue you might have received more additional info about that.
I was actually trying to install 'master' instead of the release on the right side. The official release for Blender 3 with latest Blender works just fine and I was able to install it and start using it. My bad.

Great job!
